### ISSUE TITLE
chrome loads but doesn't go to web page

### ISSUE THREAD

**Issue by rubycut** [admc/jellyfish#15]
```
node_modules/.bin/jellyfish chrome
(chrome): http.createClient is deprecated. Use `http.request` instead.

undefined

```

Try opening page:

```
(chrome): browser.go("http://jelly.io")
{ startURL: 'http://jelly.io/',
  tid: '3e60e911-2ab6-4545-86f6-cd5ae21729ca',
  tentacles: 
   { '3e60e911-2ab6-4545-86f6-cd5ae21729ca': 
      { ArrayBuffer: [Function: ArrayBuffer],
        Int8Array: [Object],
        Uint8Array: [Object],
        Uint8ClampedArray: [Object],
        Int16Array: [Object],
        Uint16Array: [Object],
        Int32Array: [Object],
        Uint32Array: [Object],
        Float32Array: [Object],
        Float64Array: [Object],
        DataView: [Function: DataView],
        global: [Circular],
        process: [Object],
        GLOBAL: [Circular],
        root: [Circular],
        Buffer: [Object],
        setTimeout: [Function],
        setInterval: [Function],
        clearTimeout: [Function],
        clearInterval: [Function],
        console: [Getter],
        firefox: [Function],
        chrome: [Function],
        safari: [Function],
        jellyfish: [Function],
        e: 'webdriver',
        m: '2',
        methodName: 'stop',
        encoding: 'utf8',
        errno: 'ENOENT' } },
  port: 48494,
  frame: null,
  live: false,
  jfComplete: false,
  queue: 
   [ { meth: 'run',
       qid: 'a3891bbe-dd02-4651-ae4b-8847b14cf3e1',
       code: 'window.location.href=\'http://jelly.io\'',
       cb: undefined } ],
  resolve: {},
  frames: {},
  config: {},
  opts: {},
  log: 
   [ [ 'output',
       'started server',
       '3e60e911-2ab6-4545-86f6-cd5ae21729ca on port 0' ],
     [ 'client error after writeHead was called. Error: getaddrinfo ENOENT\n    at errnoException (dns.js:31:11)\n    at Object.onanswer [as oncomplete] (dns.js:123:16)' ],
     [ 'client error after writeHead was called. Error: getaddrinfo ENOENT\n    at errnoException (dns.js:31:11)\n    at Object.onanswer [as oncomplete] (dns.js:123:16)' ],
     [ 'client error after writeHead was called. Error: getaddrinfo ENOENT\n    at errnoException (dns.js:31:11)\n    at Object.onanswer [as oncomplete] (dns.js:123:16)' ] ],
  startTime: 1346874087,
  start: [Function],
  name: 'chrome',
  server: 
   { _connections: 3,
     connections: [Getter/Setter],
     allowHalfOpen: true,
     _handle: 
      { writeQueueSize: 0,
        onconnection: [Function: onconnection],
        owner: [Circular] },
     _events: 
      { request: [Function],
        connection: [Function: connectionListener],
        connect: [] },
     httpAllowHalfOpen: false,
     _connectionKey: '4:0.0.0.0:0' },
  init: [Function],
  js: [Function],
  go: [Function],
  stop: [Function],
  bin: '/usr/bin/google-chrome',
  target: { start: [Function], stop: [Function] },
  bid: 'e3b8dc0d-fc23-4c6b-bbcc-6ed6fa25464f',
  instance: 
   { _closesNeeded: 3,
     _closesGot: 0,
     signalCode: null,
     exitCode: null,
     killed: false,
     _handle: 
      { owner: [Circular],
        onexit: [Function],
        pid: 28534 },
     pid: 28534,
     stdin: 
      { _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 0,
        _bytesDispatched: 0,
        allowHalfOpen: undefined,
        writable: true,
        readable: false },
     stdout: 
      { _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 0,
        _bytesDispatched: 0,
        allowHalfOpen: undefined,
        writable: false,
        readable: true,
        _paused: false,
        _events: [Object] },
     stderr: 
      { _handle: [Object],
        _pendingWriteReqs: 0,
        _flags: 0,
        _connectQueueSize: 0,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 408,
        _bytesDispatched: 0,
        allowHalfOpen: undefined,
        writable: false,
        readable: true,
        _paused: false,
        _events: [Object] },
     stdio: [ [Object], [Object], [Object] ],
     _events: { exit: [Function] } } }



```

**Comment by rubycut** [comment]
Also creates new directory where call jelly from, for example:

undefined14015941-0b37-465c-8089-a4146bd099f0
